version: '3.8'

services:
  # ✅ Custom MySQL with init.sql & my.conf
  database:
    build:
      context: ./database
    container_name: inventoryhub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3315:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inventoryhub_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # ✅ User Service
  user-service:
    build:
      context: ./user-service
    container_name: user_service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=user_service
      - GRAPHQL_PORT=5001
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inventoryhub_network

  # ✅ Inventory Service
  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory_service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=inventory_service
      - GRAPHQL_PORT=5002
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inventoryhub_network

  # ✅ Supplier Service
  supplier-service:
    build:
      context: ./supplier-service
    container_name: supplier_service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=supplier_service
      - GRAPHQL_PORT=5003
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inventoryhub_network

  # ✅ Category Service
  category-service:
    build:
      context: ./category-service
    container_name: category_service
    ports:
      - "5004:5004"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=category_service
      - GRAPHQL_PORT=5004
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inventoryhub_network

  # ✅ Notifications Service
  notifications-service:
    build:
      context: ./notifications-service
    container_name: notifications_service
    ports:
      - "5005:5005"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=notifications_service
      - GRAPHQL_PORT=5005
    depends_on:
      database:
        condition: service_healthy
    networks:
      - inventoryhub_network

  # ✅ Frontend with NGINX
  frontend:
    image: nginx:alpine
    container_name: inventoryhub_frontend
    ports:
      - "8000:80"
    volumes:
      - ./frontend/views:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - inventory-service
      - category-service
      - supplier-service
      - notifications-service
    networks:
      - inventoryhub_network

volumes:
  mysql_data:

networks:
  inventoryhub_network:
    driver: bridge
