version: "3.9"

services:
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@user-db:3306/user_db
    ports:
      - "5001:5001"
    restart: on-failure

  inventory-db:
    image: mysql:8.0
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    depends_on:
      inventory-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@inventory-db:3306/inventory_db
    ports:
      - "5002:5002"
    restart: on-failure

  supplier-db:
    image: mysql:8.0
    container_name: supplier-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supplier_db
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  supplier-service:
    build:
      context: ./supplier-service
    container_name: supplier-service
    depends_on:
      supplier-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@supplier-db:3306/supplier_db
    ports:
      - "5010:5003"
    restart: on-failure

  category-db:
    image: mysql:8.0
    container_name: category-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: category_db
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  category-service:
    build:
      context: ./category-service
    container_name: category-service
    depends_on:
      category-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@category-db:3306/category_db
    ports:
      - "5004:5004"
    restart: on-failure

  notifications-db:
    image: mysql:8.0
    container_name: notifications-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notifications_db
    ports:
      - "3311:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  notifications-service:
    build:
      context: ./notifications-service
    container_name: notifications-service
    depends_on:
      notifications-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@notifications-db:3306/notifications_db
    ports:
      - "5005:5005"
    restart: on-failure

  frontend: 
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - inventory-service
      - category-service
      - supplier-service
      - notifications-service

